name: CI

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Super-linter is a ready-to-run collection of linters and code analyzers, to help validate your source code
      - name: Super-Linter
        uses: super-linter/super-linter@v7.1.0
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
